// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const DATABASE_URL =
  process.env["DATABASE_URL"] ??
  process.env["POSTGRES_PRISMA_URL"] ??
  process.env["POSTGRES_URL"] ??
  process.env["DIRECT_URL"] ??
  process.env["POSTGRES_URL_NON_POOLING"];

if (!DATABASE_URL) {
  throw new Error(
    "Missing database connection string. Set DATABASE_URL or the Vercel Postgres variables (POSTGRES_PRISMA_URL / POSTGRES_URL)."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
