// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const DATABASE_URL =
  process.env["DATABASE_URL"] ??
  process.env["POSTGRES_PRISMA_URL"] ??
  process.env["POSTGRES_URL"] ??
  process.env["DIRECT_URL"] ??
  process.env["POSTGRES_URL_NON_POOLING"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // `prisma generate` does not need a live database connection, but Vercel runs
  // it during `npm install`. Use a placeholder URL so install can finish even
  // when runtime env vars have not been configured yet.
  datasource: DATABASE_URL
    ? {
        url: DATABASE_URL,
      }
    : {
        url: "postgresql://placeholder:placeholder@localhost:5432/placeholder",
      },
});
